### ISSUE TITLE
Missing Values Pattern Function

### ISSUE THREAD

**Issue by deshanadesai** [harshnisar/badfish#1]
mf.pattern(columns = ['Ozone', 'Temp'])
## Returns the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-23-3cc6a0177b84> in <module>()
----> 1 mf.pattern(columns = ['Ozone', 'Temp'])

/home/deshana/Desktop/BadFish/badfish/badfish/badfish.py in pattern(self, where, columns, how, norm, threshold, ascending)
    207 
    208         pat_ = mf_.groupby(mf_.columns.tolist()).size()
--> 209         pat_ = pat_.sort_values(ascending = ascending)
    210 
    211 

/usr/local/lib/python2.7/dist-packages/pandas/core/generic.pyc in **getattr**(self, name)
   2148                 return self[name]
   2149             raise AttributeError("'%s' object has no attribute '%s'" %
-> 2150                                  (type(self).**name**, name))
   2151 
   2152     def **setattr**(self, name, value):

AttributeError: 'Series' object has no attribute 'sort_values'

**Comment by deshanadesai** [comment]
The error is recurring with other functions too. How do I fix it?

**Comment by harshnisar** [comment]
It's because you are using an older version of pandas. Can you upgrade and
check?

Good catch. We need to set the minimum versions for the dependencies when
we set up for pypi.
