### ISSUE TITLE
Apriori algo error

### ISSUE THREAD

**Issue by deshanadesai** [harshnisar/badfish#5]
Error on: itemsets, rules = mf.frequency_item_set(columns = ['Ozone','Temp','Wind'], support=0.0)
## Do I need to install pymining etc?

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-43-f445dc0e3d52> in <module>()
----> 1 itemsets, rules = mf.frequency_item_set(columns = ['Ozone','Temp','Wind'], support=0)

/home/deshana/Desktop/BadFish/badfish/badfish/badfish.pyc in frequency_item_set(self, columns, support, rules, confidence, engine)
    371 
    372         # For now the same supports being used in FIM and Association Rules.
--> 373         rules = assocrules.mine_assoc_rules(item_sets, min_support=support, min_confidence=confidence)
    374 
    375         rules_df = pd.DataFrame(rules, columns = ['X =>', 'Y', 'Support', 'Confidence'])

/usr/local/lib/python2.7/dist-packages/pymining/assocrules.pyc in mine_assoc_rules(isets, min_support, min_confidence)
     12             _mine_assoc_rules(
     13                 left, right, support, visited, isets,
---> 14                 min_support, min_confidence, rules)
     15 
     16     return rules

/usr/local/lib/python2.7/dist-packages/pymining/assocrules.pyc in _mine_assoc_rules(left, right, rule_support, visited, isets, min_support, min_confidence, rules)
     26 
     27     support_a = isets[left]
---> 28     confidence = float(rule_support) / float(support_a)
     29     if confidence >= min_confidence:
     30         rules.append((left, right, rule_support, confidence))

ZeroDivisionError: float division by zero

**Comment by harshnisar** [comment]
It appears you do have pymining.

This is the airquality dataset? I will try to reproduce the error at my end.

**Comment by harshnisar** [comment]
```
itemsets, rules = mf.frequency_item_set(columns = ['Ozone','Temp','Wind'], support=0)
```

Support can't be set as zero as it breaks the following line in pymining

```
confidence = float(rule_support) / float(support_a)
```

Good catch - should make sure the user's input is >0 and <=1

**Comment by harshnisar** [comment]
Resolved.

Printed a warning and made the method return.
