### ISSUE TITLE
Cohort error

### ISSUE THREAD

**Issue by deshanadesai** [harshnisar/badfish#6]
## Does the 'group' need to be changed to 'where' in the code?

NameError                                 Traceback (most recent call last)
<ipython-input-60-839e7ec5ff92> in <module>()
----> 1 mf.cohort(group = ['Ozone'])

/home/deshana/Desktop/BadFish/badfish/badfish/badfish.pyc in cohort(self, group, columns, how)
    258             group_ = self.miss_frame[where].all(axis = 1)
    259         if how == 'any':
--> 260             group_ = self.miss_frame[where].any(axis = 1)
    261 
    262         if columns == None:

NameError: global name 'where' is not defined

**Comment by harshnisar** [comment]
Solved +1

Changed the use of where in cohort to group.
