### ISSUE TITLE
Cohort - Error

### ISSUE THREAD

**Issue by deshanadesai** [harshnisar/badfish#8]
You seem to be taking the input from args as 'Column' and then using the variable 'Where'. Check, seems inconsistent. Maybe I don't have the updated code?

Tried this code: mf.cohort(group = ['Ozone'])

---

NameError                                 Traceback (most recent call last)
<ipython-input-4-839e7ec5ff92> in <module>()
----> 1 mf.cohort(group = ['Ozone'])

/home/deshana/Desktop/BadFish/badfish/badfish/badfish.pyc in cohort(self, group, columns, how)
    258             group_ = self.miss_frame[where].all(axis = 1)
    259         if how == 'any':
--> 260             group_ = self.miss_frame[where].any(axis = 1)
    261 
    262         if columns == None:

NameError: global name 'where' is not defined

**Comment by deshanadesai** [comment]
Checked on latest code. Error persists.

**Comment by harshnisar** [comment]
Resolved. +1
